service: group-conversation #name this whatever you want
 
provider:
 name: aws
 runtime: python3.8
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
